sequenceDiagram
    actor GUT as Gutachter
    actor DRV as 8023 (DRV-MA)
    participant SMD as rvSMD<br/>System
    participant ELG as eLogin<br/>System
    participant RVG as rvGutachten<br/>System
    participant POST as Postservice
    participant EML as E-Mail<br/>Service
    
    Note over GUT,EML: UC-01 Version 4: administrierte Registrierung kompakt
    
    %% Phase 1: Initiale Interessensbekundung
    GUT->>DRV: 01. Interesse an Teilnahme bekundet
    DRV->>POST: 02. Brief zur Datenerhebung versenden
    POST-->>GUT: Brief erhalten
    
    %% Phase 2: Datensammlung
    GUT->>GUT: 03. Formular ausgefüllen<br/>(Name, EFN, E-Mail)
    GUT->>POST: 04. Formular per Brief versenden
    POST-->>DRV: Formular erhalten
    
    %% Phase 3: System-Setup durch Admin
    DRV->>SMD: 05. Daten bei Gutachter ergänzen
    SMD->>RVG: 06. Gutachter anlegen API<br/>(Name, Vorname, EFN, Träger KTAN)
    
    %% Phase 4: eLogin Account Creation
    DRV->>ELG: 07. Gutachter anlegen Dialog<br/>(Name, Vorname, Adresse, E-Mail)
    ELG->>ELG: 08. eLogin-ID + Registrierungscode generieren
    EL-->>DRV: eLogin-ID + Registrierungscode erstellt
    DRV->>RVG: 09. eLogin-ID am Gutachter ergänzen (Liste+auswählen+eintragen )
    
    %% Phase 5: Data Verification & Linking
    alt Versand per E-Mail
    ELG->>EML: 10. E-Mail mit Registrierungslink und Registrierungscode versenden
    EMAIL-->>GUT: E-Mail erhalten
    else Versand per Brief
    %% Phase 6: Postal Activation
    DRV->>POST: 11. Brief mit Registrierungslink und Registrierungscode versenden
    POST-->>GUT: Brief erhalten
    end 
    
    RVG->>RVG: 12. Gutachter anhand Name, Vorname auswählen
    RVG->>RVG: 13. Auswahl der eLoginId anhand Name, Vorname 
    RVG->>RVG: 14. Verbinden von EFN und eLoginId

    %% Phase 7: Initial eLogin Activation
    GUT->>ELG: 15. Registrierungslink öffnen
    G-->>ELG: Registrierungscode eingeben
    ELG->>GUT: 16. Passwordseite anzeigen
    G-->>ELG: Password vergeben 
    ELG->>ELG: 17. eLogin-Account aktiv
    
