sequenceDiagram
    participant SYS as System Event
    participant RG as rvGutachten System
    participant NM as Notification Manager
    participant TM as Template Manager
    participant DB as Datenbank
    participant ES as E-Mail System
    participant G as Gutachter/Benutzer

    Note over SYS,G: UC06 Automatische E-Mail-Benachrichtigungen

    SYS->>RG: 1. Triggering Event (Neuer Auftrag/Status/Mahnung)
    RG->>NM: 2. Event zur Verarbeitung weiterleiten

    NM->>DB: 3. Betroffenen Gutachter ermitteln
    DB->>NM: 4. Gutachterliste + E-Mail-Präferenzen

    alt Benutzer hat Benachrichtigungen deaktiviert
        NM->>RG: 5a. Event ignorieren (Opt-out respektieren)
    else Benachrichtigungen aktiv
        NM->>TM: 5b. Geeignetes E-Mail-Template bestimmen

        alt Neuer Auftrag zugewiesen
            TM->>TM: 6a. Template "Neuer Auftrag" laden
            TM->>DB: 7a. Auftragsdaten für Platzhalter abrufen
            DB->>TM: 8a. {{auftrag_nummer}}, {{proband_name}}, {{frist_datum}}

        else Auftragsstatus geändert
            TM->>TM: 6b. Template "Statusänderung" laden
            TM->>DB: 7b. Statusdaten abrufen
            DB->>TM: 8b. Alter/Neuer Status, Zeitstempel

        else Mahnung eingegangen
            TM->>TM: 6c. Template "Mahnung" (Priorität) laden
            TM->>DB: 7c. Mahnungsdaten abrufen
            DB->>TM: 8c. Mahnstufe, Fristdaten, Eskalationsstufe

        else System-Wartung
            TM->>TM: 6d. Template "System-Info" laden
            TM->>DB: 7d. Wartungsdetails abrufen
            DB->>TM: 8d. Wartungsfenster, betroffene Services
        end

        TM->>TM: 9. Platzhalter ersetzen ({{gutachter_name}}, {{link_portal}})
        TM->>NM: 10. Personalisierte Nachricht erstellen

        NM->>ES: 11. E-Mail versenden
        alt SMTP-Fehler
            ES->>NM: 12a. Versandfehler
            NM->>NM: 13a. Retry-Mechanismus (3 Versuche)
            alt Max. Versuche erreicht
                NM->>DB: 14a. Fehlerhafte E-Mail-Adresse markieren
                NM->>RG: 15a. Admin über Versandfehler informieren
            else Retry erfolgreich
                ES->>G: 14b. E-Mail zugestellt
                NM->>DB: 15b. Erfolgreichen Versand protokollieren
            end
        else Versand erfolgreich
            ES->>G: 12b. E-Mail zugestellt
            NM->>DB: 13b. Versand im Audit-Log protokollieren
        end
    end

    Note over SYS,G: Konfigurierbare Einstellungen

    alt Administrator konfiguriert Templates
        participant ADM as Administrator
        ADM->>TM: 16. Template bearbeiten
        TM->>DB: 17. Neue Template-Version speichern
        TM->>ADM: 18. Änderungen bestätigt

    else Gutachter ändert Präferenzen
        G->>RG: 19. Benachrichtigungseinstellungen öffnen
        RG->>DB: 20. Aktuelle Präferenzen laden
        DB->>RG: 21. Einstellungen (Frequenz, Opt-outs)
        RG->>G: 22. Einstellungsformular anzeigen

        G->>RG: 23. Präferenzen ändern (täglich/sofort/wöchentlich)
        RG->>DB: 24. Neue Präferenzen speichern
        RG->>G: 25. Änderungen bestätigt
    end
